apiVersion: apps/v1
kind: Deployment

metadata:
  name: node-frontend

spec:
  replicas: 5

  selector:
    matchLabels:
      app: node-frontend

  template:
    metadata:
      labels:
        app: node-frontend

    spec:
      containers:
        - name: node-frontend
          image: abdocker409/cricket-frontend:05
          ports:
            - containerPort: 80