input {
  file {
    path => "/usr/share/logstash/sample.log"
    start_position => "beginning"
    sincedb_path => "/dev/null"
  }
}

filter {
  grok {
    match => {
      "message" => "%{TIMESTAMP_ISO8601:timestamp} %{LOGLEVEL:level} %{GREEDYDATA:message}"
    }
  }
}

output {
  elasticsearch {
    hosts => ["http://elasticsearch1:9200"]
    index => "application-logs"
  }

  stdout {
    codec => rubydebug
  }
}