apiVersion: apps/v1
kind: Deployment

metadata:
  name: cricket-admin

spec:
  replicas: 1

  selector:
    matchLabels:
      app: cricket-admin

  template:
    metadata:
      labels:
        app: cricket-admin

    spec:
      containers:
        - name: cricket-admin

          image: abdocker409/cricket-admin:05

          imagePullPolicy: IfNotPresent

          ports:
            - containerPort: 80

          env:
            - name: VITE_API_URL
              value: "http://127.0.0.1:64834"  